# Generated by Django 3.2.7 on 2021-10-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
