# Generated by Django 3.2.8 on 2021-10-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_address_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can View History')]},
        ),
    ]
